language: cpp

os:
    - linux
    - windows

sudo: required

services:
    - docker
  
addons:
    apt:
        packages:
            - docker-ce

env:
    matrix:
        - SMBRANCH=1.8-dev
        - SMBRANCH=1.9-dev
        - SMBRANCH=master
        
before_script:
    - mkdir build
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker build -t messagebot . ; fi
    - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install -y visualstudio2017buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --add Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Win81 --add Microsoft.VisualStudio.Component.WinXP" ; fi

script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run -w /build --env SMBRANCH=$SMBRANCH -v $(pwd):/build messagebot bash build.sh ; fi
    - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then ./build.bat ; fi

cache:
    directories:
        - build-linux
        - build-windows
    
deploy:
    - provider: releases
      skip_cleanup: true
      api_key:
          secure: gqk3iV6SYdc/4MgXAwLY860GXwr9siKp67ke/5F1BpsSWPOBnq8CwkkVyGRjWhrskrXJIBYFu9n2n1BXxs5tx2iuwPVTCzAqzHlmXn5H6XAveY4Aibi7tqx9kXSX0Qhwg6lUF1LhG74/IhCTxaEpjUhadKCv3e6eGfQxdqEG/KSvCc92QJDWZmfgTap0gJiZFwOc1wJzxQrqZexbkXDgFmBBdKEM7bBaec+g99UkQBY2k8mAlZ097O6PpBLCEJnPcyD0YoAl1xCW7f7Bn7727vw0EuRVncn1JzU09WUvyJKx9FbgsxtXTtyVdeNi+UyQNZqmAVl/fwzjTF40cH8DFyQrAUE97Av19HGfGZnLLjjhJSVkQ+5U0sBbRsW0gjEhTB6639J+wadE1ZTh5XJP9dhDYq+vnmte/NddKum67Uv/DvtCtUqFrqc1uH6nR6fxWOVMa7TE6vjSgGfPGLG19ogjYpCvFecUR1B9OrS2+AAxn6ncBeFIytmCQ1uLZ8/6Xhk1KuJ6jNHwqDUUr+TWjCPjXCOaUSGeDSdVpHO+u4K2Txq5XGcjRBmevcPVkPZqgHNQN3hFlgUG/L2JiAmA1ZLzZCTrYdFPyMord+GQC7N7loQBhjUOEYo5IC9/NebmDtcPisNDoYtmFI3i4WbLaDnUQK8wulso9qKWErWQqxU=
      file:
          - Release/messagebot.ext.so
          - msvc17/Release/messagebot.ext.dll
          - ca-bundle.crt
      on:
          condition: "$SMBRANCH = 1.9-dev"
          repo: dordnung/MessageBot
          all_branches: true
          tags: true