language: cpp

sudo: required
dist: precise
addons:
    apt:
        packages:
            - lib32stdc++6
            - zip
            - unzip
            - gcc-multilib
            - g++-multilib

env:
    matrix:
        - SMBRANCH=1.8-dev
        - SMBRANCH=1.9-dev
        - SMBRANCH=master
        
before_script:
    - mkdir build
    - export MESSAGEBOT_DIR=$(pwd)
    - export BUILD_DIR=$(pwd)/build

script:
    - ldd --version
    - bash build.sh