language: cpp

sudo: required

services:
  - docker
  
addons:
    apt:
        packages:
            - docker-ce

env:
    matrix:
        - SMBRANCH=1.8-dev
        - SMBRANCH=1.9-dev
        - SMBRANCH=master
        
before_script:
    - mkdir build
    - docker build -t messagebot .

script:
    - docker run --env SMBRANCH=$SMBRANCH --env MESSAGEBOT_DIR=/build --env BUILD_DIR=/build/build -v $(pwd):/build  messagebot bash build.sh
    
deploy:
    - provider: releases
      skip_cleanup: true
      api_key:
          secure: YIVHzrwDDY+BDtcoftVC0ddFfBBDQQ+2uQlnXRe6swGq+WqhZL7tYX7OejA/ob38mZmvdZtehsNDaAIhiQuHASXz0ggGyTk/RsQ8lziDA5atx+dIJKN7jFJKeOBvMwuUnX6uN/my/D3sHONsuwQeSkqc8fdemlSYXIjeAI58lh05WjwLrlECBxrFzWY7f2kW7ehsp4rXLBfTuZlIdWwuEUefKzpZ+etCkq9auF/3F79mZrbaWaFQcrR6y0kxQFpLoWd0IQt1CLyDXZE/yYHgUuii+fGt9gnX8UUG0zbB6xVp6CBiWYZqtvwGOY60PdvuQiLoUANL5oelkXMlSIFuaCvBW2CA6mnq+Du3ViSJ6v6WFa68HCTKtObQw4lLr3tA+UxTttlDGQitXrFH+xjrTVB2oAxTckpjm1ywmsOIbsirNPcdISFmgz87Zbss1DPgqKpn/Oj0ya/ps5stTVMftPGFF6soP/r3C9xGbuTTibom4KdBPJkyiIj87bpulh98qgZvS1TvehIxnPl2Db18Kbnn/uaVYYhBhI7eHj14YH2oIGKtEeIIxchaCbvP6GHn3YwikygdIiV/Th9XaJTZCkNK9RREGCaIy4Lr+lyfRyLPUQTAG0MvaUMpaixL9JpvnNxluMUij+bKSt6xyRz31vDSuOfHg2RdPsfvfPCryBE=
      file:
          - Release/messagebot.ext.so
      on:
          condition: "$SMBRANCH = 1.9-dev"
          repo: dordnung/MessageBot
          all_branches: true