language: cpp

os:
    - linux
    - windows

sudo: required

services:
    - docker
  
addons:
    apt:
        packages:
            - docker-ce

env:
    matrix:
        - SMBRANCH=1.8-dev
        - SMBRANCH=1.9-dev
        - SMBRANCH=master
        
before_script:
    - mkdir build
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker build -t messagebot . ; fi
    - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install -y visualstudio2017buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --add Microsoft.Component.VC.Runtime.UCRTSDK --add Microsoft.VisualStudio.Component.Windows81SDK --add Microsoft.VisualStudio.Component.WinXP" ; fi

script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run -w /build --env SMBRANCH=$SMBRANCH --env MESSAGEBOT_DIR=/build --env BUILD_DIR=/build/build -v $(pwd):/build messagebot bash build.sh ; fi
    - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then ./build.bat ; fi
    
deploy:
    - provider: releases
      skip_cleanup: true
      api_key:
          secure: Onp80JCAQrsJ4mu1eP9jlOx+izuHdcMCMZMgJnsDvfL6os6FS/oOOC0EKIojBlLQlk5qkNfYR6A10fZoejY/hV7W0jfingP1R1ACeMK/ipjDgOC2MIduSIJAj6u9fb7OTzUz6UB++Qmvo68TXP9/84lWSpGyAheSsZhgI75nH0QzLE4qp2bv91RyfSrqF4eM/QFUCca5cxMslHVIz1XArqJshQgAASu+ApMFQ/zYPM8KgWcX29rg5kEe6ZGg+M5WsjxnuJQSCcNoEbgxLMu4SnEbfCT30vLlir/j0l84YfamKijQLTR+2B8bJov2X9nK+a2DvVcZZ0bA/fKSTkYbnXODytfLuVb5R/gdwHz5RPLmInEOM0oJfiKM6x53gJdZ5qspvUqWs01GMrE2UYc4urwAGaTiuEdGHdpYwZbd4HbcedvASelT4XcDw/G/Wz6dGxm8pRXunRn3ksA1trPmxXpEo/i4FbEL9GACwHXOgjoNJXlUEwluYkn8JSjJ8lWJ7vSrK006YOGMti8Bdz2T/PmI9VVWNb9sjVPXssO4K/2XFqEz/eNEQyElJ1q+TOJs3WyIn28T2cR6Hq/6r5pZNAdusFHHa80Wd61z8/h+2BtN77hQQbcV9Io8mqF1H0Gq3U0RdUipsf+Sp3hwkE4pJtC20qNdU7Wv3MsUyLr4tME=
      file:
          - Release/messagebot.ext.so
          - msvc17/Release/messagebot.ext.dll
      on:
          condition: "$SMBRANCH = 1.9-dev"
          repo: dordnung/MessageBot
          all_branches: true
          tags: true